language: java
branches:
  only:
  - develop
  - "/^release-[0-999].[0-999]$/"
  - master
notifications:
  email:
    recipients:
    - admin@liberotodo.com
  slack:
    secure: xTGvIF3x4qGx5K3WGHm52yFOCLPrwYg4XS0v1SHiScWNsP3q4g7uYbF/W8yWhvieinAaJ0p7c7wGYRrVtBErwdbiJh0zHaEckB2iKpvgQPGtF9W9JfKxrVnb5Rvs0gyb1zOfvMTFqb0szLdqkvcq/GrRgLqH6O/uXYbs1bJqCLiISkFFK2cVafcnKaoLYNXrkj5IIzPLRps2nD2T70j2lILOjqVfTZC8gDqK3N2AVd72ycl8i7rhPNZn+SFp6LpOqPOJ5oufAQoQldMEVcXWz8jrjbc3CJxLhiK+X3VZ+uMex8Vflrne1rtyLF1IkD2xKbPBJniCv+Untykgrdpq09s2FdiTNR10iheT7P8jwbhhPlFNIXVRmUblYZ/pjAVdmy5xcVZW88tJfHqnn5kiWEJi508640hgnpdvVGkfqw56sLFZ8uOUyzTZ0ntaIFa661X516u3NBKxUwypKfgFDVUzPVTL2dKA2MzhuvOGf/MfG/VxdIeCfJeY47BWQhzt0Bw1aGFvz6MUehUR40sLntJWiG9EJ+ZVKD40id3KuqkuVBmCdaYjgL6FAqjn/FQLa9JriBicVl9yxxFpIevONxnjo+SvLUTReC5ovAE6vMc+xfDL/IuSIQD4Y4D9sPKj334VKXXfqBlo//tiPkaCUqKwYribMzkzNftwnDasRHg=
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=crowded1984
  -Dsonar.login=$SONAR
deploy:
  provider: heroku
  api_key: "$HEROKU"
  skip_cleanup: true
  on:
    branch: master
